name: musicaiz

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.9
  - numpy>=1.17.0
  - jupyter
  - pip
  - coverage
  - pytest-mpl
  - pytest-cov
  - pytest

  - pip:
    - -r requirements.txt
