name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: True

jobs:
    test:
        name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                include:
                    - os: ubuntu-latest
                      python-version: "3.8"
                      channel-priority: "strict"
                      envfile: "environment.yml"

                    - os: ubuntu-latest
                      python-version: "3.9"
                      channel-priority: "strict"
                      envfile: "environment.yml"

                    - os: macos-latest
                      python-version: "3.9"
                      channel-priority: "strict"
                      envfile: "environment.yml"

                    - os: windows-latest
                      python-version: "3.9"
                      channel-priority: "strict"
                      envfile: "environment.yml"

        steps:
        - uses: actions/checkout@v2
          with:
            submodules: true


        - name: Cache conda
          uses: actions/cache@v2
          env:
            CACHE_NUMBER: 1
          with:
            path: ~/conda_pkgs_dir
            key: ${{ runner.os }}-${{ matrix.python-version }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles( matrix.envfile ) }}

        - name: Install Conda environment
          uses: conda-incubator/setup-miniconda@v2
          with:
            auto-update-conda: true
            python-version: ${{ matrix.python-version }}
            add-pip-as-python-dependency: true
            auto-activate-base: false
            activate-environment: test
            channel-priority: ${{ matrix.channel-priority }}
            environment-file: ${{ matrix.envfile }}
            use-only-tar-bz2: true

        - name: Conda info
          shell: bash -l {0}
          run: |
            conda info -a
            conda list
        - name: Install musicaiz
          shell: bash -l {0}
          run: python -m pip install --upgrade-strategy only-if-needed -e .[tests]

        - name: Run pytest
          shell: bash -l {0}
          run: pytest

        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v3
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            files: ./coverage.xml
            directory: ./coverage/reports/
            flags: unittests
            env_vars: OS,PYTHON
            name: codecov-umbrella
            fail_ci_if_error: true
            verbose: true